export const ACCOUNT = {
  REGISTER_ACCOUNT_ONLY_REQUEST: 'REGISTER_ACCOUNT_ONLY_REQUEST',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCES: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR'
};
