export const ADMIN = {
  TOGGLE_JOB_POST_MODAL: 'TOGGLE_JOB_POST_MODAL',
  TOGGLE_CREATE_PARTNER_MODAL: 'TOGGLE_CREATE_PARTNER_MODAL',
  CLOSE_ADMIN_MODALS: 'CLOSE_ADMIN_MODALS',
  SET_SELECTED_NAVIGATION: 'SET_SELECTED_NAVIGATION',

  CREATE_JOBPOST_REQUEST: 'CREATE_JOBPOST_REQUEST',
  CREATE_JOBPOST_SUCCESS: 'CREATE_JOBPOST_SUCCESS',
  CREATE_JOBPOST_ERROR: 'CREATE_JOBPOST_ERROR',

  CLEAR_JOBPOST_SUCCESS: 'CLEAR_JOBPOST_SUCCESS',
  CLEAR_JOBPOST_ERROR: 'CLEAR_JOBPOST_ERROR',

  CREATE_PARTNER_REQUEST: 'CREATE_PARTNER_REQUEST',
  CREATE_PARTNER_SUCCESS: 'CREATE_PARTNER_SUCCESS',
  CREATE_PARTNER_ERROR: 'CREATE_PARTNER_ERROR',

  CLEAR_CREATE_PARTNER_SUCCESS: 'CLEAR_CREATE_PARTNER_SUCCESS',
  CLEAR_CREATE_PARTNER_ERROR: 'CLEAR_CREATE_PARTNER_ERROR'
};
