export const ADMIN = {
    TOGGLE_JOB_POST_MODAL: 'TOGGLE_JOB_POST_MODAL',
    TOGGLE_CREATE_PARTNER_MODAL: 'TOGGLE_CREATE_PARTNER_MODAL',
    CLOSE_ADMIN_MODALS: 'CLOSE_ADMIN_MODALS',
    SET_SELECTED_NAVIGATION: 'SET_SELECTED_NAVIGATION'
}