export const PRICE = {
    PRICE_LIST_REQUEST: 'PRICE_LIST_REQUEST',
    PRICE_LIST_SUCCESS: 'PRICE_LIST_SUCCESS',
    PRICE_LIST_ERROR: 'PRICE_LIST_ERROR',

    SET_SELECTED_PRICE: 'SET_SELECTED_PRICE',
    CLEAR_SELECTED_PRICE: 'CLEAR_SELECTED_PRICE',
}